import { is } from '@magic/types'

export const isEntity = ent => {
  if (is.empty(ent) || !is.string(ent) || !ent.startsWith('&') || !ent.endsWith(';')) {
    return false
  }

  // remove first and last char, -2 is intended
  let id = ent.substr(1, ent.length - 2)

  // is numerical id
  if (id.startsWith('#')) {
    id = parseInt(id.substr(1), 10)

    return entities.some(e => e[0] === id)
  }

  // is named id
  return entities.some(e => e[2] === id)
}

export const entityFromId = id => {
  if (isEntity(id)) {
    return id
  }

  if (is.number(id)) {
    return `&#${id};`
  }

  if (!id.startsWith('&')) {
    id = `&${id}`
  }

  if (!id.endsWith(';')) {
    id += ';'
  }

  return id
}

export const entities = [
  [32, ' ', 'nbsp', 'Space'],
  [33, '!', '', 'Exclamation mark'],
  [34, '"', 'quot', 'Quotation mark'],
  [35, '#', '', 'Number sign'],
  [36, '$', '', 'Dollar sign'],
  [37, '%', '', 'Percent sign'],
  [38, '&', 'amp', 'Ampersand'],
  [39, "'", '', 'Apostrophe'],
  [40, '(', '', 'Opening/Left Parenthesis'],
  [41, ')', '', 'Closing/Right Parenthesis'],
  [42, '*', '', 'Asterisk'],
  [43, '+', '', 'Plus sign'],
  [44, ',', '', 'Comma'],
  [45, '-', '', 'Hyphen'],
  [46, '.', '', 'Period'],
  [47, '/', '', 'Slash'],
  [48, '0', '', 'Digit 0'],
  [49, '1', '', 'Digit 1'],
  [50, '2', '', 'Digit 2'],
  [51, '3', '', 'Digit 3'],
  [52, '4', '', 'Digit 4'],
  [53, '5', '', 'Digit 5'],
  [54, '6', '', 'Digit 6'],
  [55, '7', '', 'Digit 7'],
  [56, '8', '', 'Digit 8'],
  [57, '9', '', 'Digit 9'],
  [58, ':', '', 'Colon'],
  [59, ';', '', 'Semicolon'],
  [60, '<', 'lt', 'Less-than'],
  [61, '=', '', 'Equals sign'],
  [62, '>', 'gt', 'Greater than'],
  [63, '?', '', 'Question mark'],
  [64, '@', '', 'At sign'],
  [65, 'A', '', 'Uppercase A'],
  [66, 'B', '', 'Uppercase B'],
  [67, 'C', '', 'Uppercase C'],
  [68, 'D', '', 'Uppercase D'],
  [69, 'E', '', 'Uppercase E'],
  [70, 'F', '', 'Uppercase F'],
  [71, 'G', '', 'Uppercase G'],
  [72, 'H', '', 'Uppercase H'],
  [73, 'I', '', 'Uppercase I'],
  [74, 'J', '', 'Uppercase J'],
  [75, 'K', '', 'Uppercase K'],
  [76, 'L', '', 'Uppercase L'],
  [77, 'M', '', 'Uppercase M'],
  [78, 'N', '', 'Uppercase N'],
  [79, 'O', '', 'Uppercase O'],
  [80, 'P', '', 'Uppercase P'],
  [81, 'Q', '', 'Uppercase Q'],
  [82, 'R', '', 'Uppercase R'],
  [83, 'S', '', 'Uppercase S'],
  [84, 'T', '', 'Uppercase T'],
  [85, 'U', '', 'Uppercase U'],
  [86, 'V', '', 'Uppercase V'],
  [87, 'W', '', 'Uppercase W'],
  [88, 'X', '', 'Uppercase X'],
  [89, 'Y', '', 'Uppercase Y'],
  [90, 'Z', '', 'Uppercase Z'],
  [91, '[', '', 'Opening/Left square bracket'],
  [92, '\\', '', 'Backslash'],
  [93, ']', '', 'Closing/Right square bracket'],
  [94, '^', '', 'Caret'],
  [95, '_', '', 'Underscore'],
  [96, '`', '', 'Grave accent'],
  [97, 'a', '', 'Lowercase a'],
  [98, 'b', '', 'Lowercase b'],
  [99, 'c', '', 'Lowercase c'],
  [100, 'd', '', 'Lowercase d'],
  [101, 'e', '', 'Lowercase e'],
  [102, 'f', '', 'Lowercase f'],
  [103, 'g', '', 'Lowercase g'],
  [104, 'h', '', 'Lowercase h'],
  [105, 'i', '', 'Lowercase i'],
  [106, 'j', '', 'Lowercase j'],
  [107, 'k', '', 'Lowercase k'],
  [108, 'l', '', 'Lowercase l'],
  [109, 'm', '', 'Lowercase m'],
  [110, 'n', '', 'Lowercase n'],
  [111, 'o', '', 'Lowercase o'],
  [112, 'p', '', 'Lowercase p'],
  [113, 'q', '', 'Lowercase q'],
  [114, 'r', '', 'Lowercase r'],
  [115, 's', '', 'Lowercase s'],
  [116, 't', '', 'Lowercase t'],
  [117, 'u', '', 'Lowercase u'],
  [118, 'v', '', 'Lowercase v'],
  [119, 'w', '', 'Lowercase w'],
  [120, 'x', '', 'Lowercase x'],
  [121, 'y', '', 'Lowercase y'],
  [122, 'z', '', 'Lowercase z'],
  [123, '{', '', 'Opening/Left curly brace'],
  [124, '|', '', 'Vertical bar'],
  [125, '}', '', 'Closing/Right curly brace'],
  [126, '~', '', 'Tilde'],
  [160, ' ', 'nbsp', 'Non-breaking space'],
  [161, '¡', 'iexcl', 'Inverted exclamation mark'],
  [162, '¢', 'cent', 'Cent'],
  [163, '£', 'pound', 'Pound'],
  [164, '¤', 'curren', 'Currency'],
  [165, '¥', 'yen', 'Yen'],
  [166, '¦', 'brvbar', 'Broken vertical bar'],
  [167, '§', 'sect', 'Section'],
  [168, '¨', 'uml', 'Spacing diaeresis'],
  [169, '©', 'copy', 'Copyright'],
  [170, 'ª', 'ordf', 'Feminine ordinal indicator'],
  [171, '«', 'laquo', 'Opening/Left angle quotation mark'],
  [172, '¬', 'not', 'Negation'],
  [173, '­', 'shy', 'Soft hyphen'],
  [174, '®', 'reg', 'Registered trademark'],
  [175, '¯', 'macr', 'Spacing macron'],
  [176, '°', 'deg', 'Degree'],
  [177, '±', 'plusmn', 'Plus or minus'],
  [178, '²', 'sup2', 'Superscript 2'],
  [179, '³', 'sup3', 'Superscript 3'],
  [180, '´', 'acute', 'Spacing acute'],
  [181, 'µ', 'micro', 'Micro'],
  [182, '¶', 'para', 'Paragraph'],
  [184, '¸', 'cedil', 'Spacing cedilla'],
  [185, '¹', 'sup1', 'Superscript 1'],
  [186, 'º', 'ordm', 'Masculine ordinal indicator'],
  [187, '»', 'raquo', 'Closing/Right angle quotation mark'],
  [188, '¼', 'frac14', 'Fraction 1/4'],
  [189, '½', 'frac12', 'Fraction 1/2'],
  [190, '¾', 'frac34', 'Fraction 3/4'],
  [191, '¿', 'iquest', 'Inverted question mark'],
  [192, 'À', 'Agrave', 'Capital a with grave accent'],
  [193, 'Á', 'Aacute', 'Capital a with acute accent'],
  [194, 'Â', 'Acirc', 'Capital a with circumflex accent'],
  [195, 'Ã', 'Atilde', 'Capital a with tilde'],
  [196, 'Ä', 'Auml', 'Capital a with umlaut'],
  [197, 'Å', 'Aring', 'Capital a with ring'],
  [198, 'Æ', 'AElig', 'Capital ae'],
  [199, 'Ç', 'Ccedil', 'Capital c with cedilla'],
  [200, 'È', 'Egrave', 'Capital e with grave accent'],
  [201, 'É', 'Eacute', 'Capital e with acute accent'],
  [202, 'Ê', 'Ecirc', 'Capital e with circumflex accent'],
  [203, 'Ë', 'Euml', 'Capital e with umlaut'],
  [204, 'Ì', 'Igrave', 'Capital i with grave accent'],
  [205, 'Í', 'Iacute', 'Capital i with accute accent'],
  [206, 'Î', 'Icirc', 'Capital i with circumflex accent'],
  [207, 'Ï', 'Iuml', 'Capital i with umlaut'],
  [208, 'Ð', 'ETH', 'Capital eth (Icelandic)'],
  [209, 'Ñ', 'Ntilde', 'Capital n with tilde'],
  [210, 'Ò', 'Ograve', 'Capital o with grave accent'],
  [211, 'Ó', 'Oacute', 'Capital o with accute accent'],
  [212, 'Ô', 'Ocirc', 'Capital o with circumflex accent'],
  [213, 'Õ', 'Otilde', 'Capital o with tilde'],
  [214, 'Ö', 'Ouml', 'Capital o with umlaut'],
  [215, '×', 'times', 'Multiplication'],
  [216, 'Ø', 'Oslash', 'Capital o with slash'],
  [217, 'Ù', 'Ugrave', 'Capital u with grave accent'],
  [218, 'Ú', 'Uacute', 'Capital u with acute accent'],
  [219, 'Û', 'Ucirc', 'Capital u with circumflex accent'],
  [220, 'Ü', 'Uuml', 'Capital u with umlaut'],
  [221, 'Ý', 'Yacute', 'Capital y with acute accent'],
  [222, 'Þ', 'THORN', 'Capital thorn (Icelandic)'],
  [223, 'ß', 'szlig', 'Lowercase sharp s (German)'],
  [224, 'à', 'agrave', 'Lowercase a with grave accent'],
  [225, 'á', 'aacute', 'Lowercase a with acute accent'],
  [226, 'â', 'acirc', 'Lowercase a with circumflex accent'],
  [227, 'ã', 'atilde', 'Lowercase a with tilde'],
  [228, 'ä', 'auml', 'Lowercase a with umlaut'],
  [229, 'å', 'aring', 'Lowercase a with ring'],
  [230, 'æ', 'aelig', 'Lowercase ae'],
  [231, 'ç', 'ccedil', 'Lowercase c with cedilla'],
  [232, 'è', 'egrave', 'Lowercase e with grave accent'],
  [233, 'é', 'eacute', 'Lowercase e with acute accent'],
  [234, 'ê', 'ecirc', 'Lowercase e with circumflex accent'],
  [235, 'ë', 'euml', 'Lowercase e with umlaut'],
  [236, 'ì', 'igrave', 'Lowercase i with grave accent'],
  [237, 'í', 'iacute', 'Lowercase i with acute accent'],
  [238, 'î', 'icirc', 'Lowercase i with circumflex accent'],
  [239, 'ï', 'iuml', 'Lowercase i with umlaut'],
  [240, 'ð', 'eth', 'Lowercase eth (Icelandic)'],
  [241, 'ñ', 'ntilde', 'Lowercase n with tilde'],
  [242, 'ò', 'ograve', 'Lowercase o with grave accent'],
  [243, 'ó', 'oacute', 'Lowercase o with acute accent'],
  [244, 'ô', 'ocirc', 'Lowercase o with circumflex accent'],
  [245, 'õ', 'otilde', 'Lowercase o with tilde'],
  [246, 'ö', 'ouml', 'Lowercase o with umlaut'],
  [247, '÷', 'divide', 'Divide'],
  [248, 'ø', 'oslash', 'Lowercase o with slash'],
  [249, 'ù', 'ugrave', 'Lowercase u with grave accent'],
  [250, 'ú', 'uacute', 'Lowercase u with acute accent'],
  [251, 'û', 'ucirc', 'Lowercase u with circumflex accent'],
  [252, 'ü', 'uuml', 'Lowercase u with umlaut'],
  [253, 'ý', 'yacute', 'Lowercase y with acute accent'],
  [254, 'þ', 'thorn', 'Lowercase thorn (Icelandic)'],
  [255, 'ÿ', 'yuml', 'Lowercase y with umlaut'],
  [338, 'Œ', 'OElig', 'Uppercase ligature OE'],
  [339, 'œ', 'oelig', 'Lowercase ligature OE'],
  [352, 'Š', 'Scaron', 'Uppercase S with caron'],
  [353, 'š', 'scaron', 'Lowercase S with caron'],
  [376, 'Ÿ', 'Yuml', 'Capital Y with diaeres'],
  [402, 'ƒ', 'fnof', 'Lowercase with hook'],
  [710, 'ˆ', 'circ', 'Circumflex accent'],
  [732, '˜', 'tilde', 'Tilde'],
  [913, 'Α', 'Alpha', 'Alpha'],
  [914, 'Β', 'Beta', 'Beta'],
  [915, 'Γ', 'Gamma', 'Gamma'],
  [916, 'Δ', 'Delta', 'Delta'],
  [917, 'Ε', 'Epsilon', 'Epsilon'],
  [918, 'Ζ', 'Zeta', 'Zeta'],
  [919, 'Η', 'Eta', 'Eta'],
  [920, 'Θ', 'Theta', 'Theta'],
  [921, 'Ι', 'Iota', 'Iota'],
  [922, 'Κ', 'Kappa', 'Kappa'],
  [923, 'Λ', 'Lambda', 'Lambda'],
  [924, 'Μ', 'Mu', 'Mu'],
  [925, 'Ν', 'Nu', 'Nu'],
  [926, 'Ξ', 'Xi', 'Xi'],
  [927, 'Ο', 'Omicron', 'Omicron'],
  [928, 'Π', 'Pi', 'Pi'],
  [929, 'Ρ', 'Rho', 'Rho'],
  [931, 'Σ', 'Sigma', 'Sigma'],
  [932, 'Τ', 'Tau', 'Tau'],
  [933, 'Υ', 'Upsilon', 'Upsilon'],
  [934, 'Φ', 'Phi', 'Phi'],
  [935, 'Χ', 'Chi', 'Chi'],
  [936, 'Ψ', 'Psi', 'Psi'],
  [937, 'Ω', 'Omega', 'Omega'],
  [945, 'α', 'alpha', 'alpha'],
  [946, 'β', 'beta', 'beta'],
  [947, 'γ', 'gamma', 'gamma'],
  [948, 'δ', 'delta', 'delta'],
  [949, 'ε', 'epsilon', 'epsilon'],
  [950, 'ζ', 'zeta', 'zeta'],
  [951, 'η', 'eta', 'eta'],
  [952, 'θ', 'theta', 'theta'],
  [953, 'ι', 'iota', 'iota'],
  [954, 'κ', 'kappa', 'kappa'],
  [955, 'λ', 'lambda', 'lambda'],
  [956, 'μ', 'mu', 'mu'],
  [957, 'ν', 'nu', 'nu'],
  [958, 'ξ', 'xi', 'xi'],
  [959, 'ο', 'omicron', 'omicron'],
  [960, 'π', 'pi', 'pi'],
  [961, 'ρ', 'rho', 'rho'],
  [962, 'ς', 'sigmaf', 'sigmaf'],
  [963, 'σ', 'sigma', 'sigma'],
  [964, 'τ', 'tau', 'tau'],
  [965, 'υ', 'upsilon', 'upsilon'],
  [966, 'φ', 'phi', 'phi'],
  [967, 'χ', 'chi', 'chi'],
  [968, 'ψ', 'psi', 'psi'],
  [969, 'ω', 'omega', 'omega'],
  [977, 'ϑ', 'thetasym', 'Theta symbol'],
  [978, 'ϒ', 'upsih', 'Upsilon symbol'],
  [982, 'ϖ', 'piv', 'Pi symbol'],
  [8194, ' ', 'ensp', 'En space'],
  [8195, ' ', 'emsp', 'Em space'],
  [8201, ' ', 'thinsp', 'Thin space'],
  [8204, '', 'zwnj', 'Zero width non-joiner'],
  [8205, '', 'zwj', 'Zero width joiner'],
  [8211, '–', 'ndash', 'En dash'],
  [8212, '—', 'mdash', 'Em dash'],
  [8216, '‘', 'lsquo', 'Left single quotation mark'],
  [8217, '’', 'rsquo', 'Right single quotation mark'],
  [8218, '‚', 'sbquo', 'Single low-9 quotation mark'],
  [8220, '“', 'ldquo', 'Left double quotation mark'],
  [8221, '”', 'rdquo', 'Right double quotation mark'],
  [8222, '„', 'bdquo', 'Double low-9 quotation mark'],
  [8224, '†', 'dagger', 'Dagger'],
  [8225, '‡', 'Dagger', 'Double dagger'],
  [8226, '•', 'bull', 'Bullet'],
  [8230, '…', 'hellip', 'Horizontal ellipsis'],
  [8240, '‰', 'permil', 'Per mille'],
  [8242, '′', 'prime', 'Minutes (Degrees)'],
  [8243, '″', 'Prime', 'Seconds (Degrees)'],
  [8249, '‹', 'lsaquo', 'Single left angle quotation'],
  [8250, '›', 'rsaquo', 'Single right angle quotation'],
  [8254, '‾', 'oline', 'Overline'],
  [8364, '€', 'euro', 'Euro'],
  [8482, '™', 'trade', 'Trademark'],
  [8592, '←', 'larr', 'Left arrow'],
  [8593, '↑', 'uarr', 'Up arrow'],
  [8594, '→', 'rarr', 'Right arrow'],
  [8595, '↓', 'darr', 'Down arrow'],
  [8596, '↔', 'harr', 'Left right arrow'],
  [8629, '↵', 'crarr', 'Carriage return arrow'],
  [8704, '∀', 'forall', 'For all'],
  [8706, '∂', 'part', 'Part'],
  [8707, '∃', 'exist', 'Exist'],
  [8709, '∅', 'empty', 'Empty'],
  [8711, '∇', 'nabla', 'Nabla'],
  [8712, '∈', 'isin', 'Is in'],
  [8713, '∉', 'notin', 'Not in'],
  [8715, '∋', 'ni', 'Ni'],
  [8719, '∏', 'prod', 'Product'],
  [8721, '∑', 'sum', 'Sum'],
  [8722, '−', 'minus', 'Minus'],
  [8727, '∗', 'lowast', 'Asterisk (Lowast)'],
  [8730, '√', 'radic', 'Square root'],
  [8733, '∝', 'prop', 'Proportional to'],
  [8734, '∞', 'infin', 'Infinity'],
  [8736, '∠', 'ang', 'Angle'],
  [8743, '∧', 'and', 'And'],
  [8744, '∨', 'or', 'Or'],
  [8745, '∩', 'cap', 'Cap'],
  [8746, '∪', 'cup', 'Cup'],
  [8747, '∫', 'int', 'Integral'],
  [8756, '∴', 'there4', 'Therefore'],
  [8764, '∼', 'sim', 'Similar to'],
  [8773, '≅', 'cong', 'Congurent to'],
  [8776, '≈', 'asymp', 'Almost equal'],
  [8800, '≠', 'ne', 'Not equal'],
  [8801, '≡', 'equiv', 'Equivalent'],
  [8804, '≤', 'le', 'Less or equal'],
  [8805, '≥', 'ge', 'Greater or equal'],
  [8834, '⊂', 'sub', 'Subset of'],
  [8835, '⊃', 'sup', 'Superset of'],
  [8836, '⊄', 'nsub', 'Not subset of'],
  [8838, '⊆', 'sube', 'Subset or equal'],
  [8839, '⊇', 'supe', 'Superset or equal'],
  [8853, '⊕', 'oplus', 'Circled plus'],
  [8855, '⊗', 'otimes', 'Circled times'],
  [8869, '⊥', 'perp', 'Perpendicular'],
  [8901, '⋅', 'sdot', 'Dot operator'],
  [8968, '⌈', 'lceil', 'Left ceiling'],
  [8969, '⌉', 'rceil', 'Right ceiling'],
  [8970, '⌊', 'lfloor', 'Left floor'],
  [8971, '⌋', 'rfloor', 'Right floor'],
  [9674, '◊', 'loz', 'Lozenge'],
  [9824, '♠', 'spades', 'Spade'],
  [9827, '♣', 'clubs', 'Club'],
  [9829, '♥', 'hearts', 'Heart'],
  [9830, '♦', 'diams', 'Diamond'],
]

export default entities
